//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Argopt")]
[assembly: AssemblyDescription("Command line argument parsing in .NET")]
[assembly: AssemblyProduct("Argopt")]
[assembly: AssemblyCopyright("Copyright (c) Tommy Montgomery 2011")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("f2b0a567-e948-4e87-8bb8-e00430fbd260")]
[assembly: AssemblyVersion("1.0.10")]
[assembly: AssemblyFileVersion("1.0.10")]


